#source "http://rubygems.org"
source "http://gems.rubyforge.org"

#gem 'cucumber', '0.9.4'
gem 'cucumber', '0.10.0'

#gem 'capybara', '0.4.1.2'
#gem 'capybara', '0.4.0'
gem 'capybara', '1.0.0.rc1'


gem 'gizmo', '0.1.1'
gem 'rspec', '1.3.0' #'2.0.5'
gem 'net-sftp', '2.0.5'
gem 'rainbow'
gem 'ruby-debug'
#gem 'activesupport', '2.3.10'
gem 'rake', '0.8.7'
gem 'selenium-webdriver', '0.2.1'

### windows specific gems ###
platforms :mswin, :mingw do
    gem  'win32console', '1.3.0'
end
