# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.
puts "\n"

require 'rubygems'
require 'rake'

#load lib/tasks rake tasks

Dir["#{File.dirname(__FILE__)}/lib/tasks/**/*.rake"].sort.each { |t| load t }







puts "\n"